#include"../CSGO_offsets.h"
#include"IClientEntity.hpp"
#include"IVModelInfoClient.hpp"
#include"math.hpp"
#include"VMatrix.hpp"
#include"IClientInterface.h"
#include"IVEngineClient.hpp"
#include"Color.hpp"
#include"IPanel.hpp"
#include"ISurface.hpp"
#include"usercmd.h"
#include"QAngle.hpp"
#include"Enums.hpp"
#include"IAppSystem.hpp"
#include"IClientRenderable.hpp"
#include"C_BasePlayer.h"
#include"Studio.hpp"
#pragma once

